[[redirects]]
  from = "/wave/*"
  to = "https://fervent-galileo-636f72.netlify.app/:splat"
  status = 200


[[redirects]]
  from = "/bots"
  to = "/2021/06/08/how-to-build-a-friendly-social-bot/"
  status = 301

[[redirects]]
  from = "/tutorial-2021"
  to = "/2018/07/15/node-js-installieren-und-einen-webserver-starten/"
  status = 301

[[redirects]]
  from = "/python-tutorial-2021"
  to = "/2021/26/08/mit-dem-terminal-arbeiten-und-python-installieren/"
  status = 301

[[redirects]]
  from = "/kurse/gratis"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/webentwicklerin-werden"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/dein-weg-in-die-webentwicklung"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/ueber-mich"
  to = "/"
  status = 301

[[redirects]]
  from = "/kurse/blog"
  to = "/"
  status = 301

[[redirects]]
  from = "/kurse/kontakt"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/kurse/gratis-webinar"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/roadmap"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/newsletter"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/rike.dev-Roadmap.pdf"
  to = "/rike.dev-Roadmap.pdf"
  status = 301

[[redirects]]
  from = "/kurse/rike.dev-Webinar.pdf"
  to = "/rike.dev-Webinar.pdf"
  status = 301

[[redirects]]
  from = "/kurse/rike.dev-Syllabus.pdf"
  to = "/kurse/"
  status = 301

[[redirects]]
  from = "/kurse/xPuezr6542"
  to = "/xPuezr6542/"
  status = 301

  [[redirects]]
  from = "/kurse/kostenloses-erstgespraech"
  to = "/kurse/"
  status = 301

  [[redirects]]
  from = "/kurse/buchungsseite"
  to = "/kurse/"
  status = 301
  
  [[redirects]]
  from = "/kurse/replay"
  to = "/kurse/"
  status = 301
  
  [[redirects]]
  from = "/2022/19/03/hack-the-web3-building-a-worlde-on-the-blockchain*"
  to = "/2022/19/03/hack-the-web3-building-a-wordle-on-the-blockchain/"
  status = 301
  

